In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import random

def gerar_dataset_vendas(n_registros=200, seed=42):
    """Gera um dataset sintético de vendas com dados intencionalmente sujos."""
    random.seed(seed)
    np.random.seed(seed)

    produtos = ["Notebook", "Smartphone", "Tablet", "Monitor", "Teclado", "Mouse", "Headset"]
    categorias = {
        "Notebook": "Computadores",
        "Smartphone": "Celulares",
        "Tablet": "Celulares",
        "Monitor": "Computadores",
        "Teclado": "Periféricos",
        "Mouse": "Periféricos",
        "Headset": "Periféricos"
    }

    regioes = ["Sudeste", "Sul", "Nordeste", "Centro-Oeste", "Norte"]
    clientes = [f"Cliente_{i:03d}" for i in range(1, 51)]

    data_inicio = datetime(2024, 1, 1)
    dados = []

    for i in range(n_registros):

        produto = random.choice(produtos)
        quantidade = random.randint(1, 10)

        preco_base = {
            "Notebook": 3500,
            "Smartphone": 2200,
            "Tablet": 1800,
            "Monitor": 1200,
            "Teclado": 250,
            "Mouse": 120,
            "Headset": 350
        }[produto]

        preco = round(preco_base * random.uniform(0.85, 1.15), 2)
        data = data_inicio + timedelta(days=random.randint(0, 364))

        # Inserindo dados intencionalmente sujos para limpeza
        if random.random() < 0.05:
            quantidade = None
        if random.random() < 0.04:
            preco = None
        if random.random() < 0.03:
            produto = "  " + produto

        dados.append({
            "id_venda": i + 1,
            "data_venda": data.strftime("%Y-%m-%d") if random.random() > 0.02 else "DATA INVÁLIDA",
            "cliente": random.choice(clientes),
            "produto": produto,
            "categoria": categorias.get(produto.strip(), "Outros"),
            "regiao": random.choice(regioes),
            "quantidade": quantidade,
            "preco_unitario": preco
        })

    return pd.DataFrame(dados)

# Gerar e salvar dataset
df_bruto = gerar_dataset_vendas()
df_bruto.to_csv("vendas.csv", index=False)

print(f"Dataset gerado com {len(df_bruto)} registros.")
print(df_bruto.head(5))

Dataset gerado com 200 registros.
   id_venda  data_venda      cliente     produto     categoria    regiao  \
0         1  2024-05-20  Cliente_035       Mouse   Periféricos   Sudeste
1         2  2024-02-17  Cliente_042     Teclado   Periféricos     Norte
2         3  2024-05-22  Cliente_022     Monitor  Computadores  Nordeste
3         4  2024-06-21  Cliente_017  Smartphone     Celulares   Sudeste
4         5  2024-07-12  Cliente_024       Mouse   Periféricos     Norte

   quantidade  preco_unitario
0         2.0          102.90
1         7.0          214.88
2         4.0             NaN
3         4.0         2501.76
4         8.0          121.30

In [3]:
df_bruto[['produto','preco_unitario']]

        produto  preco_unitario
0         Mouse          102.90
1       Teclado          214.88
2       Monitor             NaN
3    Smartphone         2501.76
4         Mouse          121.30
..          ...             ...
195    Notebook         3279.72
196       Mouse          108.83
197     Monitor         1184.60
198      Tablet         1534.42
199     Monitor         1225.30

[200 rows x 2 columns]

In [4]:
df_bruto[['produto','preco_unitario']]

        produto  preco_unitario
0         Mouse          102.90
1       Teclado          214.88
2       Monitor             NaN
3    Smartphone         2501.76
4         Mouse          121.30
..          ...             ...
195    Notebook         3279.72
196       Mouse          108.83
197     Monitor         1184.60
198      Tablet         1534.42
199     Monitor         1225.30

[200 rows x 2 columns]

In [5]:
valor_series = pd.Series(df_bruto['preco_unitario'])

In [6]:
valor_series

0       102.90
1       214.88
2          NaN
3      2501.76
4       121.30
        ...
195    3279.72
196     108.83
197    1184.60
198    1534.42
199    1225.30
Name: preco_unitario, Length: 200, dtype: float64

In [7]:
df_bruto.shape

(200, 8)

In [8]:
df_bruto.columns

Index(['id_venda', 'data_venda', 'cliente', 'produto', 'categoria', 'regiao',
       'quantidade', 'preco_unitario'],
      dtype='str')

In [9]:
df_bruto.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        200 non-null    int64
 1   data_venda      200 non-null    str
 2   cliente         200 non-null    str
 3   produto         200 non-null    str
 4   categoria       200 non-null    str
 5   regiao          200 non-null    str
 6   quantidade      194 non-null    float64
 7   preco_unitario  190 non-null    float64
dtypes: float64(2), int64(1), str(5)
memory usage: 12.6 KB

In [10]:
df_bruto.isnull().sum()

id_venda           0
data_venda         0
cliente            0
produto            0
categoria          0
regiao             0
quantidade         6
preco_unitario    10
dtype: int64

In [11]:
df_bruto.describe()

         id_venda  quantidade  preco_unitario
count  200.000000  194.000000      190.000000
mean   100.500000    5.427835     1337.999789
std     57.879185    2.792931     1128.654914
min      1.000000    1.000000      102.900000
25%     50.750000    3.000000      264.015000
50%    100.500000    6.000000     1209.295000
75%    150.250000    8.000000     1991.257500
max    200.000000   10.000000     3996.800000

In [12]:
df_bruto.head()

,id_venda,data_venda,cliente,produto,categoria,regiao,quantidade,preco_unitario
0,1,2024-05-20,Cliente_035,Mouse,Periféricos,Sudeste,2.0,102.90
1,2,2024-02-17,Cliente_042,Teclado,Periféricos,Norte,7.0,214.88
2,3,2024-05-22,Cliente_022,Monitor,Computadores,Nordeste,4.0,NaN
3,4,2024-06-21,Cliente_017,Smartphone,Celulares,Sudeste,4.0,2501.76
4,5,2024-07-12,Cliente_024,Mouse,Periféricos,Norte,8.0,121.30

In [13]:
df = df_bruto.copy()

In [14]:
df.head()

,id_venda,data_venda,cliente,produto,categoria,regiao,quantidade,preco_unitario
0,1,2024-05-20,Cliente_035,Mouse,Periféricos,Sudeste,2.0,102.90
1,2,2024-02-17,Cliente_042,Teclado,Periféricos,Norte,7.0,214.88
2,3,2024-05-22,Cliente_022,Monitor,Computadores,Nordeste,4.0,NaN
3,4,2024-06-21,Cliente_017,Smartphone,Celulares,Sudeste,4.0,2501.76
4,5,2024-07-12,Cliente_024,Mouse,Periféricos,Norte,8.0,121.30

In [15]:
def inspecionar_dados(df):
    """Exibe informações básicas do DataFrame."""
    print("\n=== INSPEÇÃO INICIAL DO DATASET ===")
    print(f"Shape: {df.shape}")
    print(f"\nColunas: {list(df.columns)}")
    print(f"\nTipos de dados:\n{df.dtypes}")
    print(f"\nValores nulos por coluna:\n{df.isnull().sum()}")
    print(f"\nPrimeiros registros:\n{df.head()}")
    print(f"\nEstatísticas descritivas:\n{df.describe()}")

In [16]:
inspecionar_dados(df)

=== INSPEÇÃO INICIAL DO DATASET ===
Shape: (200, 8)

Colunas: ['id_venda', 'data_venda', 'cliente', 'produto', 'categoria', 'regiao', 'quantidade', 'preco_unitario']

Tipos de dados:
id_venda            int64
data_venda            str
cliente               str
produto               str
categoria             str
regiao                str
quantidade        float64
preco_unitario    float64
dtype: object

Valores nulos por coluna:
id_venda           0
data_venda         0
cliente            0
produto            0
categoria          0
regiao             0
quantidade         6
preco_unitario    10
dtype: int64

Primeiros registros:
   id_venda  data_venda      cliente     produto     categoria    regiao  \
0         1  2024-05-20  Cliente_035       Mouse   Periféricos   Sudeste
1         2  2024-02-17  Cliente_042     Teclado   Periféricos     Norte
2         3  2024-05-22  Cliente_022     Monitor  Computadores  Nordeste
3         4  2024-06-21  Cliente_017  Smartphone     Celulares   Sudeste
4         5  2024-07-12  Cliente_024       Mouse   Periféricos     Norte

   quantidade  preco_unitario
0         2.0          102.90
1         7.0          214.88
2         4.0             NaN
3         4.0         2501.76
4         8.0          121.30

Estatísticas descritivas:
         id_venda  quantidade  preco_unitario
count  200.000000  194.000000      190.000000
mean   100.500000    5.427835     1337.999789
std     57.879185    2.792931     1128.654914
min      1.000000    1.000000      102.900000
25%     50.750000    3.000000      264.015000
50%    100.500000    6.000000     1209.295000
75%    150.250000    8.000000     1991.257500
max    200.000000   10.000000     3996.800000

In [17]:
import re

def limpar_dados(df):
    """
    Limpa e trata o DataFrame de vendas.
    Retorna o DataFrame limpo e um relatório de limpeza.
    """
    n_inicial = len(df)
    relatorio = {}

    # 1. Remover espaços extras em colunas de texto
    colunas_texto = df.select_dtypes(include="object").columns
    for col in colunas_texto:
        df[col] = df[col].str.strip()

    # 2. Converter data e remover datas inválidas
    df["data_venda"] = pd.to_datetime(df["data_venda"], errors="coerce")
    n_datas_invalidas = df["data_venda"].isnull().sum()
    df = df.dropna(subset=["data_venda"])
    relatorio["datas_invalidas_removidas"] = n_datas_invalidas

    # 3. Remover linhas com quantidade ou preço nulos
    n_antes = len(df)
    df = df.dropna(subset=["quantidade", "preco_unitario"])
    relatorio["linhas_nulas_removidas"] = n_antes - len(df)

    # 4. Garantir tipos numéricos corretos
    df["quantidade"] = df["quantidade"].astype(int)
    df["preco_unitario"] = df["preco_unitario"].astype(float)

    n_final = len(df)
    relatorio["registros_iniciais"] = n_inicial
    relatorio["registros_finais"] = n_final
    relatorio["registros_removidos_total"] = n_inicial - n_final

    print("\n=== RELATÓRIO DE LIMPEZA ===")
    for chave, valor in relatorio.items():
        print(f"  {chave}: {valor}")
        return df, relatorio

In [18]:
limpar_dados(df)

=== RELATÓRIO DE LIMPEZA ===
  datas_invalidas_removidas: 4

C:\Users\PC\AppData\Local\Temp\ipykernel_4776\3459720878.py:12: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  colunas_texto = df.select_dtypes(include="object").columns

(     id_venda data_venda      cliente     produto     categoria        regiao  \
 0           1 2024-05-20  Cliente_035       Mouse   Periféricos       Sudeste
 1           2 2024-02-17  Cliente_042     Teclado   Periféricos         Norte
 3           4 2024-06-21  Cliente_017  Smartphone     Celulares       Sudeste
 4           5 2024-07-12  Cliente_024       Mouse   Periféricos         Norte
 5           6 2024-04-26  Cliente_025  Smartphone     Celulares      Nordeste
 ..        ...        ...          ...         ...           ...           ...
 195       196 2024-07-15  Cliente_021    Notebook  Computadores         Norte
 196       197 2024-03-22  Cliente_002       Mouse   Periféricos       Sudeste
 197       198 2024-05-03  Cliente_042     Monitor  Computadores  Centro-Oeste
 198       199 2024-02-25  Cliente_024      Tablet     Celulares       Sudeste
 199       200 2024-04-09  Cliente_036     Monitor  Computadores      Nordeste

      quantidade  preco_unitario
 0             2          102.90
 1             7          214.88
 3             4         2501.76
 4             8          121.30
 5             2         1900.24
 ..          ...             ...
 195           1         3279.72
 196           6          108.83
 197           9         1184.60
 198           9         1534.42
 199           1         1225.30

 [180 rows x 8 columns],
 {'datas_invalidas_removidas': np.int64(4),
  'linhas_nulas_removidas': 16,
  'registros_iniciais': 200,
  'registros_finais': 180,
  'registros_removidos_total': 20})